---
version: "2.0"

services:
  xray-server:
    image: ubuntu:22.04
    expose:
      - port: 443
        as: 443
        to:
          - global: true
    command:
      - bash
      - "-c"
      - |
        # Install dependencies
        apt-get update && apt-get install -y curl jq openssl uuid-runtime
        
        # Install Xray-core
        curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh | bash
        
        # Generate keys
        mkdir -p /usr/local/etc/xray
        
        # Generate UUID
        UUID=$(cat /proc/sys/kernel/random/uuid)
        
        # Generate X25519 keys
        KEYS=$(xray x25519)
        PRIVATE_KEY=$(echo "$KEYS" | grep "PrivateKey:" | awk '{print $2}')
        PUBLIC_KEY=$(echo "$KEYS" | grep "PublicKey:" | awk '{print $2}')
        
        # Short ID
        SHORT_ID=$(openssl rand -hex 4)
        
        # Create config
        cat > /usr/local/etc/xray/config.json << XRAYCONFIG
        {
          "log": {
            "loglevel": "warning"
          },
          "inbounds": [
            {
              "port": 443,
              "protocol": "vless",
              "settings": {
                "clients": [
                  {
                    "id": "$UUID",
                    "flow": "xtls-rprx-vision"
                  }
                ],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                  "show": false,
                  "dest": "www.google.com:443",
                  "xver": 0,
                  "serverNames": ["www.google.com"],
                  "privateKey": "$PRIVATE_KEY",
                  "shortIds": ["$SHORT_ID"]
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "tag": "direct"
            }
          ]
        }
        XRAYCONFIG
        
        # Output credentials for retrieval
        echo "=== AKASH DEPLOYMENT CREDENTIALS ===" > /credentials.txt
        echo "UUID: $UUID" >> /credentials.txt
        echo "PUBLIC_KEY: $PUBLIC_KEY" >> /credentials.txt
        echo "SHORT_ID: $SHORT_ID" >> /credentials.txt
        echo "HOSTNAME: $(hostname -I | awk '{print $1}')" >> /credentials.txt
        cat /credentials.txt
        
        # Start Xray
        exec xray run -config /usr/local/etc/xray/config.json
    
    params:
      storage:
        data:
          mount: /data
          readOnly: false

profiles:
  compute:
    xray-server:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0dgjwl9e7hjnxuw0t3qj6c"
      pricing:
        xray-server:
          denom: uakt
          amount: 10000

deployment:
  xray-server:
    akash:
      profile: xray-server
      count: 1
